#include "api-libjade.h"

#define CRYPTO_SECRETKEYBYTES 2464
#define CRYPTO_PUBLICKEYBYTES 1216
#define CRYPTO_CIPHERTEXTBYTES 1120
#define CRYPTO_KEYPAIRCOINBYTES 96
#define CRYPTO_ENCCOINBYTES 64
#define CRYPTO_BYTES 32